[build]
  # functions = "functions/"
  command = "sed -i s/DAILY_API_KEY_PLACEHOLDER/${DAILY_API_KEY}/g netlify.toml"

[template.environment]
  DAILY_API_KEY = "Replace with API key"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[[redirects]]
  from = "/api/rooms"
  to = "https://api.daily.co/v1/rooms"
  status = 200
  force = true
  headers = {Authorization = "Bearer DAILY_API_KEY_PLACEHOLDER"}